# Generated by Django 3.2 on 2021-04-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
