# Generated by Django 3.2 on 2021-04-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='snippet',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
