# Generated by Django 3.2 on 2021-04-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20210415_0028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
