# Generated by Django 3.2 on 2021-04-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_delete_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='resume',
            field=models.FileField(null=True, upload_to='books/pdf'),
        ),
    ]
